# Generated by Django 5.1.4 on 2025-03-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='samlinger',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
