# Generated by Django 5.1.4 on 2025-03-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimApp', '0002_product_samlinger'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=20)),
                ('collection_description', models.CharField(max_length=20)),
                ('collection_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='samlinger',
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection_products',
            field=models.ManyToManyField(to='pimApp.collections'),
        ),
    ]
