# Generated by Django 5.1.4 on 2025-03-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimApp', '0004_product_category_product_product_type_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20)),
                ('supplier_description', models.CharField(max_length=20)),
                ('supplier_image', models.ImageField(upload_to='')),
                ('supplier_address', models.CharField(max_length=20)),
                ('supplier_phone', models.CharField(max_length=20)),
                ('supplier_email', models.CharField(max_length=20)),
                ('supplier_website', models.CharField(max_length=20)),
                ('supplier_contact_person', models.CharField(max_length=20)),
                ('supplier_contact_phone', models.CharField(max_length=20)),
                ('supplier_contact_email', models.CharField(max_length=20)),
                ('supplier_contact_position', models.CharField(max_length=20)),
                ('supplier_notes', models.CharField(max_length=20)),
            ],
        ),
    ]
