# Generated by Django 5.1.4 on 2025-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pimApp', '0008_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='supplier_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
